version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    env_file: ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-padmin"]
      interval: 5s
      timeout: 5s
      retries: 15
    ports:
      - "3306:3306"

  app:
    container_name: ecommerce-app
    build:
      context: .
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mysql-data:
