services:
  app:
    container_name: ecommerce-app-v2
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env/app.env
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

  app2:
    container_name: ecommerce-app-v3
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env/app2.env
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - ecommerce-net

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    networks:
      - ecommerce-net

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge